name: VirusTotal Scan

on:
  release:
    types: [published]

jobs:
  scan:
    runs-on: ubuntu-latest
    steps:
      - name: Scan installer with VirusTotal
        uses: crazy-max/ghaction-virustotal@v4
        with:
          vt_api_key: ${{ secrets.VT_API_KEY }}
          files: |
            ${{ github.event.release.assets[0].browser_download_url }}
